services:
  traefik:
    image: traefik:3.0
    ports:
      - 80:80 # HTTP port
      - 443:443 # HTTPS port
      - 8080:8080 # Dashboard
    restart: always
    labels:
      # Traefik configuration
      - traefik.enable=true
      - traefik.docker.network=traefik-public

      # HTTP router configuration for dashboard
      - traefik.http.routers.traefik-dashboard.entrypoints=http
      - traefik.http.routers.traefik-dashboard.rule=Host(`traefik.${DOMAIN?Variable not set}`)
      - traefik.http.routers.traefik-dashboard.service=api@internal
      
      # HTTPS router configuration for dashboard
      - traefik.http.routers.traefik-dashboard-https.entrypoints=https
      - traefik.http.routers.traefik-dashboard-https.rule=Host(`traefik.${DOMAIN?Variable not set}`)
      - traefik.http.routers.traefik-dashboard-https.service=api@internal
      - traefik.http.routers.traefik-dashboard-https.tls=true
      - traefik.http.routers.traefik-dashboard-https.tls.certresolver=le
      
      # Basic Auth for dashboard
      - traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME:-admin}:${HASHED_PASSWORD:-$$2y$$05$$wHZkNF6e8g29dWtSJ0pNh.55UfmYwzlr4UFZsePQp0hFDHLxLeweO}
      - traefik.http.routers.traefik-dashboard.middlewares=https-redirect,admin-auth
      - traefik.http.routers.traefik-dashboard-https.middlewares=admin-auth
      
      # Redirect HTTP to HTTPS
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Docker socket for reading service labels
      - ./certificates:/certificates # Volume for storing Let's Encrypt certificates
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL:-your-cloudflare-email@example.com}
      # Use either API_KEY or DNS_API_TOKEN (not both)
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY:-}
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN:-}
    command:
      # Docker provider configuration
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik-public

      # Entrypoints configuration
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443

      # Let's Encrypt configuration with Cloudflare DNS challenge
      - --certificatesresolvers.le.acme.email=${ACME_EMAIL:-your-email@example.com}
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.dnschallenge=true
      - --certificatesresolvers.le.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.le.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53

      # Dashboard configuration
      - --api.dashboard=true
      
      # Logging configuration
      - --accesslog
      - --log
    networks:
      - traefik-public # Public network for Traefik and other services

networks:
  traefik-public:
    external: true # Use pre-existing traefik-public network
