services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "60"
      - "--rolling-restart"
    environment:
      # Direct registry authentication
      - REGISTRY_USER=_json_key_base64
      - REGISTRY_PASS=${GOOGLE_APPLICATION_CREDENTIALS_BASE64}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  portfolio:
    # For production, use your private image
    image: asia-southeast2-docker.pkg.dev/mamenesia/images/portfolio:release
    container_name: portfolio
    restart: always
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.http.routers.portfolio-http.rule=Host(`mamenesia.com`)
      - traefik.http.routers.portfolio-http.entrypoints=http
      # Removed the https-redirect middleware to prevent redirect loops
      - traefik.http.routers.portfolio-https.rule=Host(`mamenesia.com`)
      - traefik.http.routers.portfolio-https.entrypoints=https
      - traefik.http.routers.portfolio-https.tls=true
      - traefik.http.routers.portfolio-https.tls.certresolver=le
      - traefik.http.routers.portfolio-https.service=portfolio-service
      - traefik.http.services.portfolio-service.loadbalancer.server.port=3000
      - com.centurylinklabs.watchtower.enable=true

volumes:
  storage:

networks:
  traefik-public:
    external: true
